# Generated by Django 3.2.9 on 2022-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_uuid', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Is email verified')),
                ('is_active', models.BooleanField(default=False, verbose_name='User is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Late Updated date')),
            ],
            options={
                'get_latest_by': ['id'],
            },
        ),
    ]
