# Generated by Django 3.2.9 on 2022-11-13 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(default=[], related_name='_user_user_follow_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
